### ISSUE TITLE
Blank Screen when you select Bookings overview on moodle v3.0

### ISSUE THREAD

**Issue by demontech** [dasistwas/moodle-block_booking#1]
![image](https://cloud.githubusercontent.com/assets/8148238/17162481/4fd9e220-536b-11e6-8aaa-c9c42001ff79.png)

**Comment by dasistwas** [comment]
There is no official support for M3.0 right now. Also it might not work with current versions of the booking module. There is currently no funding for updating the block and it may be discontinued.

**Comment by dasistwas** [comment]
New version should fix that for M3.1 to M3.3.
