### ISSUE TITLE
My Bookings Link - blank

### ISSUE THREAD

**Issue by demontech** [dasistwas/moodle-block_booking#2]
Hi David,

Thank you for updating this block to work with mod booking. I have installed it in M3.3, and signing is as student the "My bookings" link doesn't take you anywhere.

![image](https://user-images.githubusercontent.com/8148238/33395821-9004b218-d4fb-11e7-999d-b9294916d6f5.png)

Thanks!!

**Comment by dasistwas** [comment]
Hi,
I just fixed that problem: Fix is in mod_booking and block_booking. So please update both.
Kind regards,
David
